package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"golang.org/x/tools/go/packages"
)

const reverseMappingTemplate = `
// Code generated by "reverse_stringer"; DO NOT EDIT.
package {{.PackageName}}

import "fmt"

var _{{.TypeName}}fromString = map[string]{{.TypeName}}{
	{{- range $k, $v:= .Enums}}
	"{{$k}}": {{$v}},
	{{- end}}
}

func Parse{{.TypeName}}(s string) ({{.TypeName}}, error) {
	if val, ok := _{{.TypeName}}fromString[s]; ok {
		return val, nil
	}

	return 0, fmt.Errorf("invalid {{.TypeName}}: %s", s)
}
`

type templateObject struct {
	PackageName string
	TypeName    string
	Enums       map[string]any
}

var (
	rootCmd = &cobra.Command{
		Use:   "reverse_stringer",
		Short: "a simple reverse mapping generator for stringer",
		RunE: func(cmd *cobra.Command, args []string) error {
			if silenceFlag {
				log.SetOutput(io.Discard)
			}
			if cmd.Flags().Changed("working-dir") {
				if st, err := os.Stat(workingDir); err != nil {
					return err
				} else if !st.IsDir() {
					return fmt.Errorf(`working dir %s is not a directory`, workingDir)
				}
				os.Chdir(workingDir)
			}
			return reverseMap()
		},
	}
	enumType        string
	packageName     string
	moduleString    string
	workingDir      string
	lineCommentFlag bool
	stdoutFlag      bool
	silenceFlag     bool
)

func main() {
	// Execute the root command
	if err := rootCmd.Execute(); err != nil {
		log.Println(err)
		os.Exit(1)
	}

}

func init() {
	rootCmd.Flags().StringVarP(&enumType, "enum-type", "e", "", "enum type")
	rootCmd.MarkFlagRequired("enum-type")
	rootCmd.Flags().StringVarP(&packageName, "package-name", "p", "", "package containing the enum")
	rootCmd.MarkFlagRequired("package-name")
	rootCmd.Flags().StringVarP(&moduleString, "module", "m", "", `module string e.g. "example.com/user/module123"`)
	rootCmd.Flags().BoolVar(&lineCommentFlag, "line-comment", false, "use the line comment as name")
	rootCmd.Flags().StringVarP(&workingDir, "working-dir", "w", "", "working dir")
	rootCmd.Flags().BoolVar(&stdoutFlag, "stdout", false, "write to stdout instead to file")
	rootCmd.Flags().BoolVarP(&silenceFlag, "silent", "s", false, "silent output")
}

// function used to pre filter for the enum
func packageHasEnum(pkg *packages.Package, moduleStr string, pkgStr string, enumStr string) bool {
	if pkg == nil {
		panic(`missing package`)
	}
	//pkgpath may contain dashes!
	if moduleStr != "" && pkg.PkgPath != moduleStr {
		return false
	}
	if !strings.HasSuffix(pkgStr, pkg.Name) {
		return false
	}
	obj := pkg.Types.Scope().Lookup(enumStr)
	if obj == nil {
		return false
	}
	_, ok := obj.Type().(*types.Named)
	return ok
}

// get the enum within a package if available. if pkgStr contains / it is assumed that the full module path is contained. otherwise just the package name from the go source.
func getEnumFromPackage(pkg *packages.Package, moduleStr string, pkgStr string, enumStr string) map[string]any {
	if pkg == nil {
		panic(`missing package`)
	}
	var m map[string]any = map[string]any{}
	for _, obj := range pkg.TypesInfo.Defs {
		c, ok := obj.(*types.Const)
		//ensure existence
		if !ok || !packageHasEnum(pkg, moduleStr, pkgStr, enumStr) {
			continue
		}
		if n, ok := obj.Type().(*types.Named); !ok {
			continue
		} else if cname := n.Obj().Name(); cname != enumStr {
			continue
		}
		m[c.Name()] = c.Val()
	}
	return m
}

func getEnum(moduleStr string, pkgStr string, enumStr string) (map[string]any, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, errors.Join(ErrPackageLoad, err)
	}
	var pkgCandidates []*packages.Package
	//1. check for enum existence in pkg
	for _, pkg := range pkgs {
		if !packageHasEnum(pkg, moduleStr, pkgStr, enumStr) {
			continue
		}
		pkgCandidates = append(pkgCandidates, pkg)
	}
	//3. check if unambiguous or no hits
	switch len(pkgCandidates) {
	case 0:
		return nil, errors.Join(ErrNoEnumFound, fmt.Errorf(`no hit for pkg "%s" and enum "%s"`, pkgStr, enumStr))
	case 1:
	default:
		var files []string
		for _, pkg := range pkgCandidates {
			files = append(files, strings.Join(pkg.GoFiles, ", "))
		}
		return nil, errors.Join(ErrAmbigousEnums, fmt.Errorf(`no unambigous hits for pkg "%s" and enum "%s". see:`+"\n%s", pkgStr, enumStr, strings.Join(files, ", ")))
	}
	//2. get constant values
	pkg := pkgCandidates[0]
	m := getEnumFromPackage(pkg, moduleStr, pkgStr, enumStr)
	if lineCommentFlag {
		remap := getCommentMapping(pkg)
		translatedM := map[string]any{}
		for k := range m {
			translatedM[remap[k]] = m[k]
		}
		return translatedM, nil
	} else {
		return m, nil
	}
}
func getCommentMapping(pkg *packages.Package) map[string]string {
	if pkg == nil {
		panic(`missing package`)
	}
	comments := map[string]string{}
	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.CONST {
				continue
			}

			for _, spec := range gen.Specs {
				vs := spec.(*ast.ValueSpec)

				var comment string
				if vs.Comment != nil {
					comment = strings.TrimPrefix(vs.Comment.Text(), "//")
					comment = strings.TrimSpace(comment)
				}

				for _, name := range vs.Names {
					//add default mapping if empty
					if comment == "" {
						comments[name.Name] = name.Name
					} else {
						comments[name.Name], _, _ = strings.Cut(comment, " ")
					}
				}
			}
		}
	}
	return comments
}

var (
	ErrNoEnumFound   = errors.New(`no enum found`)
	ErrAmbigousEnums = errors.New(`ambigous enum. try using the full package module string with the package name appended`)
	ErrPackageLoad   = errors.New(`Failed to load go packages`)
)

func reverseMap() error {
	enum, err := getEnum(moduleString, packageName, enumType)
	if err != nil {
		return err
	}

	//create elements to be templated
	tObj := &templateObject{
		PackageName: packageName,
		TypeName:    enumType,
		Enums:       map[bool]map[string]any{true: enum, false: {}}[enum != nil],
	}

	//create generated file
	var buf bytes.Buffer
	tmpl := template.Must(template.New("reverseMapping").
		Parse(reverseMappingTemplate))
	if err := tmpl.Execute(&buf, tObj); err != nil {
		return err
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting failed: %v", err)
	}
	// Write result
	switch stdoutFlag {
	case false:
		newFile := filepath.Join(filepath.Dir(packageName), fmt.Sprintf("%s_reverse_string.go", strings.ToLower(enumType)))
		if err := os.WriteFile(newFile, formatted, 0644); err != nil {
			return fmt.Errorf("file write failed: %v", err)
		}
		log.Println("Reverse mapping file generated!")
	case true:
		fmt.Println(string(formatted))
	}

	return nil
}
